language: node_js
node_js:
- '5'

deploy:
  - provider: npm
    email: serveradmin@octoblu.com
    api_key:
      secure: DNRvH4yLm3OrbAypLTW0KJFysSxmnCym7gzqjU5InQL4ai9e9DNymw+Ff1b5DnHy3sxcdq+5YqkOfd1M9Tun0DKspyd48mXPkHEt0NLDtRsr+/fot3FwbnPuWaOFmjlfNp0HrRh8H2TCQVaDW/Mbaiwm1tCWbZ4dl5njhrtKQCAW9FJSxhHfPppJbixy+L2V1dICrxDdbaQZe2vvrL2n7OlS7EZvBS5i3uI3OQWSnAMmRJuwlvmu+mRn1yC7YpoJeGErEKs3PD3frlo7J+fLh4WUZCtpuVdcVymmOiA98DeRFhrhOjjpuDE/BBSe9jhvfs8b83XiJfN3L4nrefrcXpptZ0lXnGnwj70H2TjCID3EBeVwztTMMr3AILHmpulmrjr8ztJj+mjujONl2P42AuTzrFASu/xi1AnyyGDk71F+nzA9REKEKN89Xy0kN4jHGF+GnhC6i7JA/ZTo+OOZQdqkgcvwTrP2dA2lWt0feUDlstwtaEoPzUTwDL/nvXLgZDSdrJkSEf/0EYbjhLyxK3jeaU9M8Em3pnj73Txe2fmx0h9XVH7oheONGYIIQlUjuZuXbP8kDnLooYUrptdsh3YGKL6ZlbL2PRSb4iFDsIAxiJgCOfLZ5f+DUwPRZkBnpzo4IAzuDJfnHRq54c+USiEal8waYNfpxqUv4XtHQvk=
    on:
      tags: true
      branches: true
