language: node_js
node_js:
- '5'

before_deploy:
- npm install browserify coffeeify
- mkdir -p deploy/meshblu-device-schema-transmogrifier/latest
- mkdir -p deploy/meshblu-device-schema-transmogrifier/$TRAVIS_TAG
- node_modules/.bin/browserify -s MeshbluDeviceSchemaTransmogrifier -t coffeeify src/transmogrifier.coffee > deploy/meshblu-device-schema-transmogrifier/latest/meshblu-device-schema-transmogrifier.bundle.js
- gzip deploy/meshblu-device-schema-transmogrifier/latest/meshblu-device-schema-transmogrifier.bundle.js
- mv deploy/meshblu-device-schema-transmogrifier/latest/meshblu-device-schema-transmogrifier.bundle.js.gz  deploy/meshblu-device-schema-transmogrifier/latest/meshblu-device-schema-transmogrifier.bundle.js
- cp deploy/meshblu-device-schema-transmogrifier/latest/meshblu-device-schema-transmogrifier.bundle.js deploy/meshblu-device-schema-transmogrifier/$TRAVIS_TAG/meshblu-device-schema-transmogrifier.bundle.js


deploy:
  - provider: npm
    email: serveradmin@octoblu.com
    api_key:
      secure: DNRvH4yLm3OrbAypLTW0KJFysSxmnCym7gzqjU5InQL4ai9e9DNymw+Ff1b5DnHy3sxcdq+5YqkOfd1M9Tun0DKspyd48mXPkHEt0NLDtRsr+/fot3FwbnPuWaOFmjlfNp0HrRh8H2TCQVaDW/Mbaiwm1tCWbZ4dl5njhrtKQCAW9FJSxhHfPppJbixy+L2V1dICrxDdbaQZe2vvrL2n7OlS7EZvBS5i3uI3OQWSnAMmRJuwlvmu+mRn1yC7YpoJeGErEKs3PD3frlo7J+fLh4WUZCtpuVdcVymmOiA98DeRFhrhOjjpuDE/BBSe9jhvfs8b83XiJfN3L4nrefrcXpptZ0lXnGnwj70H2TjCID3EBeVwztTMMr3AILHmpulmrjr8ztJj+mjujONl2P42AuTzrFASu/xi1AnyyGDk71F+nzA9REKEKN89Xy0kN4jHGF+GnhC6i7JA/ZTo+OOZQdqkgcvwTrP2dA2lWt0feUDlstwtaEoPzUTwDL/nvXLgZDSdrJkSEf/0EYbjhLyxK3jeaU9M8Em3pnj73Txe2fmx0h9XVH7oheONGYIIQlUjuZuXbP8kDnLooYUrptdsh3YGKL6ZlbL2PRSb4iFDsIAxiJgCOfLZ5f+DUwPRZkBnpzo4IAzuDJfnHRq54c+USiEal8waYNfpxqUv4XtHQvk=
    on:
      tags: true
      branches: true

  - provider: s3
    access_key_id: AKIAJIBYB2JBGPDSWGAQ
    secret_access_key:
      secure: Goj9sZijBhZf5dMDeB7JCHGChvVBODryv9WJ88xWNNOQJvTkORXSAbetNhFQuibLjNrIzT6WwK5U7cHUQ88MWxDPrkZHoGGw5p7Af7OWZ+Wo00T/Omtl0cwkhvGnEJvWy7G0TlTa2UIAj6XjowESjy7rbvMuY+tQypm/Q5L2zhY7iZWBKCdj1us0YVmTRjZJOzkQUyFSx1IzwTbi4dyINy21/P6FRXZ1RKzNCI3iP912AFHpBUonV6IPZ+9LToAWWfFdlidaX0nQnkzH1Q051deBk9nnM/SrtwEhqZf+kGHazBPH/fWEKHY7W65LaKC4m3tB2IRCN9898D/LoLBY8BF5iBxjPMdBD62nA5ptmrY1iC4G2K8B46aoCcX3l27e7YJcRVUCyzPxwC4RDnTKHl6D40nj2zlRCDfruMLA3XPpXckDU8aRZ/cXMYPrblbsMGAIL9p6l3dIxotTyf+dAg/ZinOqVNNsNCItuMLWmY+D8gfUz1My4VjZLwc1gx9K393eGVtG3bISGx6MzJFRHDVjt41iHQvDox9NaiLa66o2oET0+fOIaNNPd6NoOGSRU9gbJ/WfKtbtJwNo9y3TBQSXZc5VIfkuL0NmrSqG5sx/T+FsoUSynXzmkYquljtwbievea1zOKwwv/vAuHYApw5g757bi4a3f5ULlIzFA08=
    bucket: octoblu-cdn
    region: us-west-2
    skip_cleanup: true
    local-dir: deploy
    detect_encoding: true
    upload-dir: js
    on:
      tags: true
      all_branches: true
